Salesforce Assignment/Salesforce_Assignment_12/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Custom_Status__c</fullName>
        <label>Custom Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reset</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Assignment/Salesforce_Assignment_7/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Salesforce Assignment/Salesforce_Assignment_13/src/classes/testForTrigger6.cls
@isTest
public class testForTrigger6 {

    @testSetup static void opportunityTest(){
            Date date1=Date.newInstance(1960, 3, 17);
          Product2 product=new Product2(Name='prd1',price__c=2000,IsActive = true);
       
        insert product;
 System.debug(product);
          Id pricebookId = Test.getStandardPricebookId();
        PricebookEntry pbEntry= new PricebookEntry(Product2Id=product.Id,UnitPrice=7687, Pricebook2Id=pricebookId,IsActive = true);
        
        insert pbEntry;
      System.debug(pbEntry);
        Opportunity opp=new Opportunity(Name='opp',CloseDate=date1,StageName='Prospecting',Pricebook2Id=pbEntry.Pricebook2Id);

        insert opp; 
        System.debug(opp);
         List<OpportunityLineItem> oppNewP=new List<OpportunityLineItem>();
        oppNewP=[Select Id from OpportunityLineItem where OpportunityId=: opp.Id];
        System.debug('Hghfghgf'+ oppNewP);
    }
    @isTest static void checkOpportunityLineItem(){
        Opportunity opp1=[Select id,Custom_status__c from Opportunity where Name='opp'];
        System.debug(opp1);
        test.startTest();
        opp1.Custom_Status__c='Reset';
         Database.SaveResult result=database.update(opp1,false);
        List<OpportunityLineItem> oppNew=new List<OpportunityLineItem>();
        oppNew=[Select Id from OpportunityLineItem where OpportunityId=: opp1.Id];
       System.assertEquals(0,oppNew.size());
        test.stopTest();
        
        
        
        
        
    }   
    
}