Salesforce Assignment/Salesforce_Assignment_12/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BillToContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Salesforce Assignment/Salesforce_Assignment_13/src/classes/TestForOpportunityController.cls
@isTest(seeAllData=false)
private class TestForOpportunityController {
    public  static Opportunity o;
    public  static Date day ;
    @testSetup static void methodName() {
        
        
        day= date.newInstance(1990, 11, 21);
        Account acct = new Account(Name='Test Account');
        insert acct;
        Contact con = new Contact(FirstName='Test Account',LastName='vdfvj');
        insert con;
        o=new Opportunity(Name='abc',BillToContact__c=con.Id,AccountId=acct.Id,StageName='rvrgbv',CloseDate=day);
        insert o;
    }
    static testMethod void testForOpportunityTrigger() {
       
        // Verification
        Test.startTest();
        System.assertEquals('0012800000EKV94',o.Manager__c);
        
        Test.stopTest();
    }
    
}