Salesforce Assignment/Salesforce_Assignment_7/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

Salesforce Assignment/Salesforce_Assignment_7/src/objects/PurchaseOrder__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order_Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Total_Payment__c</fullName>
        <label>Total_Payment</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseOrder</label>
    <nameField>
        <label>PurchaseOrder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce Assignment/Salesforce_Assignment_7/src/objects/PurchaseOrderLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ESmartPack__c</fullName>
        <defaultValue>true</defaultValue>
        <label>ESmartPack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>PurchaseOrder__c</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>PurchaseOrderLineItems</relationshipLabel>
        <relationshipName>PurchaseOrderLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <formula>UnitPrice__c  * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>UnitPrice</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>PurchaseOrderLineItem</label>
    <nameField>
        <label>PurchaseOrderLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseOrderLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Salesforce Assignment/Salesforce_Assignment_7/src/classes/ProductPurchaseController.cls
public class ProductPurchaseController {

      public List<Product2> productList{get;set;}
    public List<PurchaseOrderLineItem__c> productsToPurchase{get;set;}
    public Set<ID> productsToPurchaseItem{get;set;}
    public String productId{get;set;}
    public Integer quantity{get;set;}
    public Product2 selectedProduct{get;set;}
    public PurchaseOrder__c order{get;set;}
 	public List<PurchaseOrder__c> ListOfOrder{get;set;}    
    public boolean purchaseOrderLineItemsdisplayPopUp {get; set;}     
    public boolean purchaseOrderdisplayPopUp {get; set;}  
    public boolean informationDisplayPopUp {get; set;} 
    public boolean OrderDisplayPopUp{get;set;}
    
    
    public ProductPurchaseController(ApexPages.StandardController controller){
        purchaseOrderLineItemsdisplayPopUp = false;
        purchaseOrderdisplayPopUp = false;
        informationDisplayPopUp = false;
        OrderDisplayPopUp=false;
        getProductList();
        
        productsToPurchase = new List<PurchaseOrderLineItem__c>();
        ListOfOrder=new List<PurchaseOrder__c>();
        productsToPurchaseItem = new Set<ID>();
        
    }
    
    
    public Void getProductList(){
        string Query = 'SELECT id,name,price__c FROM Product2';
        productList = Database.query(Query);
    }
    
    public Void addToCart(){
       
        ListOfOrder=[Select id,Name,Name__c,Address__c,Phone__c,Total_Payment__c,Order_Status__c from PurchaseOrder__c];
    
        List<PurchaseOrder__c> orderList=[Select id,Name,Name__c,Address__c,Phone__c,Total_Payment__c from PurchaseOrder__c where Order_Status__c=false];
        if(orderList.size()>0){
            order=orderList.get(0);     
        }else{
            order=new PurchaseOrder__c(Name='OrderNew');
            insert order;
        }
        
        
        productsToPurchase= [Select id,name,Product__c,Quantity__c,ESmartPack__c,UnitPrice__c,TotalPrice__c from PurchaseOrderLineItem__c where OrderId__c=:order.Id];
        for(PurchaseOrderLineItem__c item:productsToPurchase){
            productsToPurchaseItem.add(item.Product__c);
        }
        
        System.debug('In add to cart');
          purchaseOrderLineItemsdisplayPopUp = true;
        if(productsToPurchaseItem.contains(productId)){
            System.debug('ashgdcfsdgvjd');
             OrderDisplayPopUp = true;
       
            for(PurchaseOrderLineItem__c productInLineItem : productsToPurchase){
                if(productInLineItem.Product__c == productId){
                    productInLineItem.Quantity__c = ++productInLineItem.Quantity__c;
                    upsert productInLineItem;
                }
         	}   
        }
        else if(productId!=null){
             OrderDisplayPopUp = true;
        selectedProduct = [Select id,name,price__C from Product2 where id=:productId];
        PurchaseOrderLineItem__c lineItem = new PurchaseOrderLineItem__c();
            System.debug(lineItem);
        lineItem.Name = selectedProduct.Name;
        lineItem.Product__c = selectedProduct.id;
        lineItem.Quantity__c = 1;
      	lineItem.UnitPrice__c = selectedProduct.price__C; 
        lineItem.OrderId__c=order.Id;
            System.debug(lineItem);
        insert lineItem;
            System.debug(lineItem);
        ID lineItemId = lineItem.id;
        PurchaseOrderLineItem__c p = [Select id,name,Product__c,Quantity__c,ESmartPack__c,UnitPrice__c,TotalPrice__c from PurchaseOrderLineItem__c where id=:lineItemId];
        productsToPurchase.add(p);
        productsToPurchaseItem.add(p.Product__c);
        }
     }    
   
     public Void removeFromCart(){
         purchaseOrderLineItemsdisplayPopUp = true;
         PurchaseOrderLineItem__c productInCart = [Select id, name,Quantity__c,ESmartPack__c,UnitPrice__c,TotalPrice__c from PurchaseOrderLineItem__c where id=:productId];
         Integer index = 0;
         for(PurchaseOrderLineItem__c purchaseOrder : productsToPurchase){
             if(purchaseOrder.Id == productInCart.Id){
                 break;
             }
               index++;
         }
         productsToPurchaseItem.remove(productsToPurchase.get(index).Product__c);
         productsToPurchase.remove(index);
      
         Delete productInCart;
    }
    
    
    public void pay(){
        for(PurchaseOrderLineItem__c purchaseOrder : productsToPurchase){
           System.debug('\nnew  '+ purchaseOrder.Quantity__c + '   '+purchaseOrder.ESmartPack__c);
           
         }
       informationDisplayPopUp = true;
        upsert productsToPurchase;
    }
    
    public void confirm(){
        order.Order_Status__c=true;
        double price=0;
         for(PurchaseOrderLineItem__c purchaseOrder : productsToPurchase){
           price= price+purchaseOrder.TotalPrice__c;
         }
        if(order.Total_Payment__c!=null){
        order.Total_Payment__c=order.Total_Payment__c+price;
        }else{
            order.Total_Payment__c=price;
        }
        system.debug(order);
            upsert order;
          system.debug(order);
         ListOfOrder=[Select id,Name,Name__c,Address__c,Phone__c,Total_Payment__c,Order_Status__c from PurchaseOrder__c];
     OrderDisplayPopUp = true;
          system.debug(ListOfOrder);
        
		productsToPurchase.clear();
        productsToPurchaseItem.clear();
        purchaseOrderLineItemsdisplayPopUp = false;
        purchaseOrderdisplayPopUp = false;
        informationDisplayPopUp = false;
    }
}